### ISSUE TITLE
能简单介绍一下如何构造的 ttf 字体吗？

### ISSUE THREAD

**Issue by jacobbubu** [junmer/source-han-serif-ttf#1]
https://github.com/adobe-fonts/source-han-serif 只有 otf 字体下载，不知道如何转到 ttf 的。

**Comment by junmer** [comment]
可以用一些字体制作软件来完成这个工作，比如
- [Glyphs](https://glyphsapp.com/)
- [FontForge](http://fontforge.github.io/)

**Comment by jacobbubu** [comment]
谢谢提供线索。
